Bulk message fetch, deletion, and example clear command.
b1naryth1ef/dscord pull request #25
Opened 2017-02-06 19:40 UTC by ZeroSumGame

This adds in the ability to get messages in bulk from the server.  I've also added in an example "clear" command, which is one of the most common features found in Discord bots.

2017-02-12 19:25 UTC, ZeroSumGame commented
Any word on this?  It's been almost a week.

2017-02-12 23:14 UTC, b1naryth1ef commented
Ah sorry I forgot to hit the submit review button.

2017-02-12 23:17 UTC, b1naryth1ef requested changes
Couple nits and minor changes

2017-02-12 23:17 UTC, b1naryth1ef commented on src/dscord/api/client.d
> +    assert(limit <= 100, "The maximum number of messages that can be deleted at one time is 100.");
This assert message seems wrong. Should also likely be a fully runtime check, assert gets compiled out in release which seems iffy for required validation stuff like this (e.g. we know the request will fail, might as well not make the HTTP round trip to Discord API servers)

2017-02-12 23:17 UTC, b1naryth1ef commented on examples/src/basic.d
> +      auto msg = event.msg.replyf("I deleted %s messages for you.", messages.length);
```d
event.msg.replyf("I deleted %s messages for you.", messages.length).after(3.seconds).del();
```

2017-02-12 23:17 UTC, b1naryth1ef commented on examples/src/basic.d
> +  void onClearMessages(CommandEvent event){
Nit; If you could make the bracket spacing line up with everything else (e.g. `) {` that would be awesome.

2017-02-12 23:17 UTC, b1naryth1ef commented on examples/src/basic.d
> +    if(event.args[].length > 0){
Why `event.args[]` and not `event.args`?

2017-02-12 23:17 UTC, b1naryth1ef commented on examples/src/basic.d
> +        limit = std.conv.to!int(event.args[0]);
preferred syntax here is just `event.args[0].to!int`

2017-02-13 00:18 UTC, ZeroSumGame commented
I believe this addresses all the issues.  There are lots of other places that this project could use some exception handling and build-time checks, TBH.

Any idea what is causing TravisCI to be upset with the builds?  Everything is working fine on the newest DMD compiler, so the build script may need updating.

2017-02-13 00:53 UTC, b1naryth1ef approved these changes

2017-02-13 01:02 UTC, merged